# Generated by Django 5.0 on 2026-01-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_client_address_invoice_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_logos/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='business_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
