# Generated by Django 5.0 on 2026-01-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_add_template_choice'),
        ('invoices', '0006_create_trash_tables'),
    ]

    operations = [
    ]
