# Generated by Django 5.0 on 2026-01-08 01:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_add_template_choice_trash'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('template_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('template_name', models.TextField()),
                ('template_layout', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoice_templates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersActivityLog',
            fields=[
                ('activity_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('activity_type', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('related_invoice', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'users_activity_logs',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='businessprofiletrash',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clienttrash',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='template_choice',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='invoicetrash',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicetrash',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoicetrash',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicetrash',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicetrash',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoicetrash',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
